# Generated by Django 5.1.1 on 2024-10-09 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_setup', '0002_alter_usermodel_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
