# Generated by Django 5.1.1 on 2024-10-09 16:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_setup', '0005_rename_potmodel_postmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='tittle',
            field=models.CharField(default=-10, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
